name: helpoo
description: خدمات طريق

publish_to: 'none'
version: 2.0.0+126

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  assets_audio_player: ^3.0.6
  audioplayers: ^3.0.1
  bloc: ^8.1.0
  bot_toast: ^4.0.3
  cached_network_image: ^3.2.3
  camera: ^0.10.0+4
  conditional_builder_null_safety: ^0.0.6
  connectivity_plus: ^3.0.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.0.1
  platform_device_id: ^1.0.1
#  bot_toast: ^4.0.3
#  get_it: ^7.2.0
#  quick_log: ^5.3.0
#  shimmer: ^2.0.0
#  hexcolor: ^3.0.1
#  font_awesome_flutter: ^10.4.0


  dotted_border: ^2.0.0+3
  double_back_to_close: ^2.0.0
  dropdown_button2: ^1.9.2
  easy_image_viewer: ^1.2.0
  easy_splash_screen: ^1.0.4
  equatable: ^2.0.5
  firebase_core: ^2.14.0
  firebase_crashlytics: ^3.3.3
  firebase_messaging: ^14.6.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_image_compress: ^1.1.3
  flutter_inappwebview: ^5.7.2+3
  flutter_local_notifications: ^13.0.0
  flutter_native_image: ^0.0.6+1
  flutter_polyline_points: ^1.0.0
  flutter_rating_bar: ^4.0.1
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.1.6
  font_awesome_flutter: ^10.4.0
  geocoding: ^2.0.4
  geolocator: ^9.0.2
  get: ^4.6.5
  get_it: ^7.2.0
  get_storage: ^2.0.3
  google_fonts: ^4.0.3
  google_maps_flutter: ^2.2.5
  google_maps_webservice: ^0.0.20-nullsafety.5
  hexcolor: ^3.0.1
  http: ^0.13.5
  image_picker: ^0.8.6
  intl: ^0.19.0
  intl_phone_number_input: ^0.7.2
  intro_slider: ^4.2.0
  location: ^5.0.0
  lottie: ^2.0.0
  map_picker: ^0.0.3
  maps_launcher: ^2.0.1
  material_design_icons_flutter: ^6.0.7096
  percent_indicator: ^4.2.2
  permission_handler: ^10.0.0
  photo_view: ^0.14.0
  quick_log: ^5.2.1
  record: ^4.4.3
#  sentry_flutter: ^7.5.0
  shimmer: ^2.0.0
  slack_notifier: ^1.2.0
  sliding_up_panel: ^2.0.0+1
  smooth_page_indicator: ^1.0.1
  syncfusion_flutter_pdfviewer: ^20.4.52
  unique_identifier: ^0.3.0
  upgrader: ^6.0.1
  url_launcher: ^6.1.6
  webview_flutter: ^4.0.7
  whatsapp_unilink: ^2.1.0

  path_provider: ^2.0.14
  pdf: ^3.10.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  # adaptive_icon_background: "assets/launcher/background.png"
  # adaptive_icon_foreground: "assets/launcher/foreground.png"

flutter:
  uses-material-design: true
  assets:
    - assets/imgs/
    - assets/report/
    - assets/lottie/
    - assets/audio/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        # - asset: fonts/Schyler-Italic.ttf
        #   style: italic
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        # - asset: fonts/TrajanPro_Bold.ttf
        #   weight: 700
    - family: Nexa
      fonts:
        - asset: assets/fonts/Nexa Light.otf
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
    - family: Proxima Nova Alt
      fonts:
        - asset: assets/fonts/Proxima Nova Alt Regular.otf
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/ProximaNova-Regular.otf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: SF Pro
      fonts:
        - asset: assets/fonts/SFPRODISPLAYREGULAR.OTF
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.ttf
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.ttf
    - family: PFDinTextArabic
      fonts:
        - asset: assets/fonts/PFDinTextArabic-Regular.ttf
    - family: GE SS
      fonts:
        - asset: assets/fonts/GE SS Two Light.otf
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeueLTArabic-Roman.ttf
    - family: Ara-Hamah
      fonts:
        - asset: assets/fonts/Ara-Hamah-1982-Regular.ttf
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
