const Map<String, String> ar = {
  "Helpoo": "هلبو",
  "After Discount": "بعد الخصم",
  "Before Discount": "قبل الخصم",
  "Voucher Code": "قسيمة حجز",
  "next": "التالى",
  "Next": "التالى",
  "Add": "ارفاق",
  "Request": "طلب",
  "NO": "لا",
  "Yes": "نعم",
  "Package Details": "تفاصيل الباقة",
  "Have Promo Code?": "لديك كود خصم؟",
  " LE / Yearly": " جنيه / سنويا",
  "Payment Process": "عملية الدفع",
  "Choose Payment": "طريقة الدفع",
  "helpoo collects location data to enable finding the nearest RSA unit. the location data is collected while the app is in use or the app is in the background":
      "تقوم هلبو بجمع بيانات الموقع لتتمكن من العثور على أقرب وحدة انقاذ لتقديم خدمة المساعدة على الطريق ويتم جمع بيانات الموقع أثناء استخدام التطبيق أو اذا كان التطبيق يعمل في الخلفية",
  "Tap To Open Report": "اضغط هنا لفتح التقرير",
  "Accident Reports": "تقارير الحادث",
  "Please capture the front side of the vehicle licence":
      "برجاء تصوير الوجهة الامامية لرخصة السيارة",
  "Please capture the back side of the vehicle licence":
      "برجاء تصوير الوجهة الخلفية لرخصة السيارة",
  "police Report Uploaded": "تم استقبال محضر شرطة",
  "Uploading Percentage": "نسبة التحميل",
  "Send Request": "ارسال الطلب",
  "Add Report": "اضافة تقرير",
  "Have reinspection Report? Please Add it": "لديك تقرير؟ برجاء ارفاقه",
  "Have supplement Report? Please Add it": "لديك تقرير؟ برجاء ارفاقه",
  "Have before Repair Report? Please Add it": "لديك تقرير؟ برجاء ارفاقه",
  "Payment Success": "تم الدفع بنجاح",
  "You Can Add Cars Now": "يمكنك اضافة السيارة الي الباقة",
  "Choose the insurance company and add a VIN Number":
      "اختر شركة التأمين واضف رقم الشاسيه",
  "VIN Number": "رقم الشاسيه",
  "pending request": "يجب عليك الاتصال بالدعم لإكمال طلبك",
  "request is pending": "الطلب معلق : ",
  "Select Company": "اختر شركة",
  "Please Select Destination": "برجاء اختيار الوجهة",
  "Insurance Policy Number": "رقم وثيقة التأمين",
  "Insurance Company": "شركة التأمين",
  "Choose insurance company": "اختيار شركة التأمين",
  "Inspection Location": "موقع المعاينة",
  "After Repair Report Updated": "تم استقبال معاينة بعد الاصلاح",
  "Is your Car Repaired and Ready for Inspection?":
      "هل تأكدت من اصلاح السيارة وجاهزيتها للمعاينة؟",
  "Bill Delivery Location": "موقع تسليم الفاتورة",
  "At time Range": "في الفترة الزمنية",
  "Bill Will Deliver At": "سيتم التسليم بتاريخ",
  "Final Data": "البيانات النهائية",
  "Billing Request Delivery Received": "تم استقبال طلب استلام فاتورة",
  "Reinspection Report Uploaded": "تم استقبال طلب معاينة جديدة",
  "Supplement Report Uploaded": "تم استقبال معاينة مقايسة اضافية",
  "Before Repair Report Uploaded": "تم استقبال طلب معاينة قبل الاصلاح",
  "Did the Vehicle Deliverd to the Work Shop and the Quotation is Ready for the Inspection?":
      "هل تم التوجه لمكان الاصلاح والتأكد من عمل مقايسة الاصلاح وان السيارة جاهزة للمعاينة؟ ",
  "Your Request has Recieved Successfully and it will be Submitted within 24 hours":
      "تم استلام طلبكم نجاح وسيتم تنفيذ طلبكم خلال ٤٨ ساعة عمل",
  "Next Step": "الخطوة التالية",
  "Vehicle Confirmation Data": "استكمال / تأكيد بيانات السيارة المؤمن عليها ",
  "Not Avaliable Yet": "خدمة غير متاحة حاليا",
  "Plate No.": "رقم اللوحة",
  "Description": "وصف الحادث",
  "Additional Photos": "صور اضافية",
  "FNOL Uploaded": "تم استقبال اخطار الحادث",
  "FNOL Follow Up": "متابعة اخطار حادث",
  "Bill Delivery Request": "طلب تسليم الفاتورة",
  "Billing Delivery": "تسليم فواتير الاصلاح",
  "Right Save Inspection": "طلب معاينة حفظ الحق",
  "After Repair Inspection": "طلب معاينة بعد الاصلاح",
  "After Repair Inspections": "معاينات بعد الاصلاح",
  "New Inspection request": "طلب معاينة جديدة",
  "Additional Inspection": "طلب معاينة اضافية (ملحق)",
  "Before Repair Request": "طلب معاينة قبل الاصلاح",
  "Before Repair Inspections": "معاينات قبل الاصلاح",
  "Add Policy Report": "ارفاق محضر الشرطة",
  "Police Report": "محضر الشرطة",
  "Please Choose Next Step": "برجاء اختيار الخطوة التالية",
  "Trip Canceled": "تم الغاء الرحلة",
  "You are Blocked": "انت محظور",
  "Something Wrong": "حدث خطأ ما",
  "instructions": "تعليمات التصوير",
  "enter": "ادخال",
  "Later": "لاحقا",
  "Home": "الصفحة الرئيسية",
  "Please Choose Destination": "برجاء اختيار الوجهة",
  "Activate": "تفعيل",
  "More": "المزيد",
  "ontinue Without Subscribtion": "متابعة بدون اشتراك",
  "Insurance policy appendix": "ملحق بوثيقة تأمين سيارة",
  "Already Have Main Package": "لدي بالفعل باقة اساسية",
  "Package Subscription": "اشتراك الباقة",
  "Yes Now": "نعم الان ",
  "Login": "تسجيل دخول",
  "Accident Report": "اخطار حادث",
  "vehicle Service Request": "طلب خدمة على الطريق",
  "Welcome": "مرحبا",
  "You have no requests now": "حاليا لا يوجد أي طلبات لك",
  "username": "اسم المستخدم",
  "password": "كلمة المرور",
  "Full Name": "الاسم بالكامل",
  "Language": "اللغة",
  "Dear Client, Do You want to Register your vehicles Now to Save Time When you Need Urgent Service?":
      "عزيزى العميل هل تريد تسجيل بيانات سيارتك الان. توفيرا للوقت عند حاجتك العاجلة للخدمة؟",
  "Settings": "اعدادات",
  "request service": '''طلب
خدمة طريق''',
  "accident report": '''إخطار
حادث''',
  "pre-inception": '''معاينة
إصدار''',
  "Request Service": "طلب خدمة",
  "Select vehicle": "حدد سيارة",
  "Batteries faults": "بطارية",
  "Tires faults": "اصلاح كاوتش",
  "Fuel faults 5L": "نقل بنزين",
  "Fuel faults 10L": "بنزين ١٠ لتر",
  "Towing": "ونش سيارة",
  "Request ID : ": "رقم الطلب",
  "canceled": "تم الغاء الطلب",
  "notAvailable": "الخدمة غير متاحة",
  "open": "مفتوح",
  "confirmed": "تم التأكيد",
  "not_available": "الخدمة غير متاحة",
  "accepted": "السائق في الطريق إليك",
  "done": "تم تنفيذ الخدمة",
  "started": "جاري تنفيذ الخدمة",
  "view": "مشاهدة",
  "Fuel": "بنزين",
  "Tire": "كاوتش",
  "Battery": "بطارية",
  "request status": "حالة الطلب",
  "fees": "التكلفة",
  "requested services": "الخدمات المطلوبة",
  "client": "العميل",
  "select pickup Address": "موقع السيارة الحالي",
  "select dropoff Address": "تحديد وجهة الوصول",
  "pickup Address": "الموقع الحالي للسيارة",
  "dropoff Address": "وجهة الوصول",
  "estimate route distance": "المسافة لمكان السيارة",
  "estimate route duration": "المدة",
  "EGP": "جنيه",
  "Active": "نشط",
  "Details": "تفاصيل",
  "Enter Email Address": "اضف البريد الالكتروني",
  "Inactive": "غير نشط",
  "Select Location": "تحديد الموقع",
  "Select Address": "اختيار العنوان",
  "Submit": "ادخال",
  "view current request": '''متابعة طلبك
الحالي''',
  "please wait for driver to accept your request": "في انتظار تأكيد السائق",
  "Request Details": "تفاصيل الطلب",
  "distance to dropoff": "المسافة لمكان التوصيل",
  "time to dropoff": "المدة للوصول لمكان التوصيل",
  "confirm": "تأكيد",
  "cancel request": "الغاء الطلب",
  "Billing Delivery Location": "مكان تسليم الفاتوره",
  "Call Driver": "الاتصال بالسائق",
  "Dropoff Directions": "الاتجاهات لوجهة الوصول",
  "Pickup Directions": "الاتجاهات لمكان العميل",
  "are you sure?": "هل انت متأكد؟",
  "yes": "نعم",
  "Done": "تم",
  "search": "بحث",
  "You are offline": "انت غير متصل بالانترنت",
  "Retry": "اعد المحاولة",
  "history": "الطلبات السابقة",
  "estimate remaining distance": "المسافة المتبقية للوصول",
  "estimate remaining duration": "الوقت المتبقي للوصول",
  "Permissions": "الصلاحيات",
  "Disable Battery Optimisation": "الغاء موفر البطارية",
  "Allow Location Access": "السماح بالحصول على الموقع",
  "vehicle is being towed": "جاري نقل السيارة",
  "back": "العودة",
  "address": "العنوان",
  "Plate NO.": "رقم اللوحة",
  "destination": "جهة الوصول",
  "on the way to client": "قي الطريق للعميل",
  "find vehicle": "البحث عن السيارة",
  "Plate NO. (optional)": "رقم اللوحة (اختياري)",
  "Notify An Accident (FNOL)": "عمل اخطار حادث",
  "number": "الرقم",
  "error": "خطأ",
  "Error": "خطأ",
  "Data Saved Successfully": "تم الحفظ بنجاح",
  "vehicle not found": "لا يوجد سيارة بهذا الرقم",
  "create report": "عمل تقرير",
  "reports history": '''التقارير
السابقة''',
  "select accident type": "اختار نوع الحادث",
  "accident report ": "اخطار الحادث",
  "Accident Types": "أنواع الحوادث",
  "vehicle owner": "صاحب السيارة",
  "Please select": "فضلا اختار",
  "insurance company": "شركة التأمين",
  "name must be at least 3 characters": "يجب الا يقل الاسم عن ٣ احرف",
  "required field": "هذه الخانة مطلوبة",
  "phone number length must be 11 degits": "رقم الهاتف يجب ان يكون ١١ رقم",
  "phone number": "رقم الهاتف",
  "report details": "التقرير المفصل",
  "new report": "تقرير جديد",
  "reports history ": "التقارير السابقة",
  "comment": "الملحوظات",
  "police report": "محضر الشرطة",
  "before repair report": "معاينة قبل الاصلاح",
  "after repair report": "معاينة بعد الاصلاح",
  "request report": "طلب معاينة",
  "Extra Photos": "الصور الإضافية",
  "Extra Photos description": "برجاء تصوير صور اضافية في الحالات التالية",
  "photos": "الصور",
  "Data Confirmation": "تأكيد البيانات",
  "save": "حفظ",
  "Save": "حفظ",
  "Promo Code Valid till": "بروموكود صالح حتي",
  "repair cost": "تكلفة الاصلاح",
  "save cost": "حفظ التكلفة",
  "current reports": "التقارير الحالية",
  "closed reports": "التقارير المنتهية",
  "vehicle owner name": "اسم صاحب السيارة",
  "add comment": "اضف ملحوظات",
  "edit comment": "تعديل الملحوظات",
  "finish": "انهاء",
  "send report": "ارسال التقرير",
  "choose accident type": "اختار الاجزاء المتضررة",
  "damaged parts": "الاجزاء المتضررة من الحادث",
  "Please select one or more type": "فضلا اختار نوع واحد على الاقل",
  "none": "لا يوجد",
  "confirm entered data": "تأكيد البيانات",
  "accident location": "موقع الحادث",
  "reports": "التقارير",
  "Service vehicle": "سيارة",
  "Scooter": "سكوتر",
  "Towing vehicle": "ونش أعطال",
  "meters": "متر",
  "Valid Promo Code": "بروموكود صحيح",
  "Replace Promo Code": "استبدل البروموكود",
  "getting your address": "جاري تحديد موقعك",
  "Set Location on Map": "حدد الموقع من الخريطة",
  "m": "متر",
  "km": "ك م",
  "Please Allow Location Access": "الرجاء تفعيل تحديد الموقع",
  "Check Again": "اعادة المحاولة",
  "Register New Account": "إنشاء حساب جديد",
  "Wrong username or password": "خطأ في اسم المستخدم أو كلمة المرور",
  "forgot password?": "نسيت كلمة المرور؟",
  "register new account": "تسجيل عضوية جديدة",
  "enter registered phone": "يرجي إدخال رقم هاتفك المحمول",
  "confirm phone number": "تأكيد رقم الهاتف",
  "enter otp": "برجاء ادخال الرقم السري المؤقت",
  "please confirm info": "يرجي تأكيد البيانات",
  "Add Vehicle": "إضافة سيارة ",
  "full name": "الاسم بالكــــامل",
  "email": "البريد الإلكتروني",
  "vehicle type": "نوع السيارة",
  "year of manufacture": "سنة الصنع",
  "model": "الموديل",
  "color": "اللون",
  "You Have No Requests For Now": "ليس لديك طلبات الان",
  "FNOL Done Successfully Uploading in Proccess":
      "تم عمل الاخطار \nجاري رفع الصور والتسجيل الصوتي",
  "FNOL Save": "حفظ الاخطار",
  "Chase Number (optional)": "رقم الشاسيه (اختياري)",
  "invalid OTP": "الرقم غير صحيح",
  "invalid otp": "الرقم غير صحيح",
  "Wrong Phone Number": "رقم الهاتف غير صحيح",
  "set password": "إنشاء كلمة المرور",
  "enter password": "برجاء ادخال كلمة المرور ",
  "password confirmation": "تأكيد كلمة المرور",
  "password length": "كلمة المرور من ٨ حروف على الأقل",
  "account success": "تم انشاء الحساب بنجاح",
  "password mismatch": "كلمة المرور غير متطابقة",
  "invalid phone number": "رقم الهاتف غير صحيح",
  "White": "أبيض",
  "Black": "أسود",
  "Gray": "رمادي",
  "Silver": "فضي",
  "Red": "أحمر",
  "Blue": "أزرق",
  "Brown": "بني",
  "Green": "أخضر",
  "Beige": "بيج",
  "Orange": "برتقالي",
  "Gold": "ذهبي",
  "Yellow": "أصفر",
  "Purple": "بنقسجي",
  "Vehicle Plate No.": "رقم اللوحة",
  "invalid email": "البريد الالكتروني غير صحيح",
  "error, number 10 - 9999": "الرقم غير صحيح",
  "please enter a valid manufacturer and vehicle model":
      "برجاء تحديد نوع و موديل السيارة",
  "Please fill in the required items": "برجاء املئ البيانات المطلوبة",
  "please enter a valid color": "برجاء تحديد لون السيارة",
  "vehicle already added": "السيارة مسجلة من قبل",
  "please select year": "برجاء تحديد سنة الصنع",
  "Edit vehicle data": "تعديل بيانات سيارة",
  "invalid name": "لا يقل عن ٣ احرف",
  "reset password page": "استرجاع كلمة المرور",
  "please enter phone number": "يرجي ادخال رقم الهاتف",
  "continue": "استمرار",
  "Continue": "متابعة",
  "Deferred": "آجل",
  "please complete missing data": "برجاء استكمال البيانات",
  "Add More Vehicle(s)": "اضافة سيارة ",
  "Please Confirm Vehicle(s) Data": "برجاء تأكيد البيانات",
  "pay driver using credit card": "دفع فيزا للسائق",
  "Online Payment": "دفع اونلاين",
  "phone number is not registered": "هذا الرقم غير مسجل لدينا",
  "pleae try again": "برجاء اعادة المحاولة",
  "password reset success": "تم تغيير كلمة المرور بنجاح",
  "please enter a valid plate number": "رقم اللوحة غير صحيح",
  "please select insurance company": "برجاء تحديد شركة التأمين",
  "vehicle added": "تم اضافة السيارة",
  "confirm payment": "تأكيد الدفع",
  "Did you recieve the payment?": "هل تسلمت المبلغ المستحق ؟",
  "service fees is": "تكلفة الخدمة",
  "paid": "تم الدفع",
  "please edit vehicle to set plate number first":
      "برجاء اضافة رقم لوحة السيارة",
  "please select services first": "برجاء تحديد الخدمة",
  "main screen": "الرئيسية",
  "please select service": "يرجي إختيار الخدمة",
  "road services": "خدمات الطريق",
  "ambulance": "إسعاف",
  "police": "النجده",
  "Wench": "ونش انقاذ",
  "latest request": "طلبات خدمة الطريق",
  "latest reports": "اخطارات الحوادث",
  "about app": "عن التطبيق",
  "my vehicles": "سياراتي",
  "packages": "الباقات",
  "contact us": "تواصل معنا",
  "not available yet": "الخدمة غير متوفرة و سيتم اطلاقها قريباً",
  "please select vehicle first": "برجاء اختيار سيارة",
  "Select Your Location": "حدد موقعك",
  "current location": "الموقع الحالي",
  "towing destination": "وجهة الونش",
  "select payment method": "حدد طريقة الدفع",
  "payment after service is done": "الدفع بعد تنفيذ الخدمة",
  "pay driver using credit vehicled": "دفع بالكارت للسائق",
  "pay driver using cash": "دفع كاش للسائق",
  "visa master card": "(ميزة - فيزا - ماستر كارد)",
  "service status": "حالة الخدمة",
  "no requests to show": "لا يوجد طلبات سابقة",
  "no reports to show": "لا يوجد اخطارات سابقة",
  "arrival time": "مدة الوصول",
  "distance": "مسافة الوصول",
  "total cost": "التكلفة النهائية",
  "basic cost": "التكلفة الأساسية",
  "minute": "دقيقة",
  "egp": "جنيه",
  "min": "دقيقة",
  "cash": "الدفع كاش",
  "vehicledToDriver": "الدفع كاش بالكارت",
  "vehicled": "بالدفع بكارت",
  "wallet": "الدفع بمحفظة",
  "please rate the driver": "يرجي تقييم السائق",
  "please click on cancel request button": "برجاء الضغط على زر الغاء الطلب",
  "sure you want to cancel": "هل تريد الغاء الطلب",
  "cancel confirmation text":
      "يمكنك الغاء الطلب في اي وقت ولن يتم تطبيق اي غرامات ولكن تجنب الالغاء المتكرر لانها تعرضك لاغلاق حسابك نهائيا ولن تستطيع فتح الحساب مرة أخري ",
  "resume": "استكمال",
  "paid success": "تمت عملية الدفع بنجاح",
  "available": "متاحة",
  "rate driver": "تقييم السائق",
  "Resume Accident Report": "متابعة اخطار حادث",
  "discount": "خصم",
  "hour": "ساعة",
  "hours": "ساعة",
  "sec": "ثانية",
  "mins": "دقائق",
  "Profile": "حسابى",
  "This Service Will be Avaiable Soon": "سيتم تفعيل هذه الخدمة قريبا",
  "If you Have Promo Code, Please insert (optional)":
      "اذا كان لديك بروموكود برجاء ادخاله (اختيارى)",
  "Choose Damaged Vehicle": "حدد السيارة المتضررة",
  "Choose one or more Accident Type": "حدد نوع حادث او أكثر",
  "You don't have registered insured vehicle": "لا تملك سيارة مؤمن عليها",
  "accident Photos": "صور الحادث",
  "attach": "ارفاق",
  "Enter Promo Code if Exist (optional)": "ادخل البروموكود ان وجد (اختياري)",
  "edit": "تعديل",
  "Edit": "تعديل",
  "add": "اضافة",
  "Loading......": "جاري التحميل......",
  "card-to-driver": "الدفع كارت للسائق",
  "online-card": "الدفع اونلاين",
  "no police report yet": "لايوجد محضر حتي الان",
  "no repair report yet": "لايوجد معاينات حتي الان",
  "arrived": " السائق وصل اليك",
  "Arrived": "لقد وصلت",
  "pay using mobile wallet": "محفظة إلكترونية",
  "pay using online vehicled": "دفع بالكارت",
  "Please Enter Mobile Number for Payment": "برجاء ادخال رقم الهاتف للدفع",
  "Pay with Mobile Wallet": "الدفع باستخدام المحفظة",
  "change language": "تغيير اللغة",
  "package name": "اسم الباقة",
  "allowed times": "عدد مرات الاستخدام",
  "maximum discount": "الخصم / الطلب",
  "discount percentage": "نسبة الخصم",
  "price": "السعر",
  "Buy Package": "اشترك الان",
  "View Package": "مشاهدة الباقة",
  "for report number ": "لإخطار حادث رقم ",
  "are you sure the vehicle has been repaired and ready to assess?":
      "هل تأكدت من اصلاح السيارة وجاهزيتها للمعاينة ؟",
  "no": "لا",
  "has the vehicle been repaired in the specified place as stated in before repair report?":
      "هل تم اصلاح السيارة في الموقع المحدد للمعاينة قبل الاصلاح ؟",
  "please contact our customer support": "يرجي الاتصال بخدمة العملاء علي",
  "customer support": "خدمة العملاء",
  "call": "اتصال",
  "your request has been received": "تم تلقي طلبكم بنجاح",
  "resend": "إعادة إرسال",
  "current package": "الباقة المشترك بها",
  "start date": "تاريخ البدء",
  "end date": "تاديخ الانتهاء",
  "used times": "عدد الطلبات المستخدمة",
  "times": " مرات",
  "payment status": "حالة الدفع",
  "pending": "في انتظار الدفع",
  "account already exists, please go to login or reset your password":
      "الرقم مسجل من قبل ، برجاء تسجيل دخول أو طلب اعادة تعيين كلمة السر",
  "sorry, we don't have inspectors available now":
      "نأسف لعدم توافر معاينين الآن",
  "sorry, service is not available now": "نأسف ، الخدمة غيد متاحة الآن",
  "send whatsapp message": "ارسال رسالة عبر الواتس اب",
  "call customer support": "الاتصال السريع بخدمة العملاء",
  "send email": "ارسال بريد إلكتروني علي البريد الإلكتروني",
  "Not Insured Text": "هذه السيارة غير مؤمن عليها",
  "Insured Text": "هذه السيارة تتمتع بخدمات هلبو حتى",
  "take photo": "التقاط الصورة",
  "Retake": "اعادة تصوير",
  "next photo": "تصوير أخري",
  "done shooting": "انهاء التصوير",
  "intro1_title": "التغطية علي مدار الساعة",
  "intro1_desc":
      "جميع الخدمات متاحة علي مدار الساعة 24/7 وفي جميع ايام العطلات الرسمية ",
  "intro2_title": "الأسهل",
  "intro2_desc":
      "بخطوات بسيطة وسهلة يمكنك طلب الخدمات بدون اي تعقيدات او خطوات اضافية ",
  "intro3_title": "الأوفر",
  "intro3_desc":
      "تحديد تكلفة النقل بدقة مسبقا من خلال التطبيق قبل الموافقة والتأكيد علي طلب وحدة الانقاذ مع امكانية الدفع كاش او اونلاين والحصول علي فاتورة الكترونية",
  "intro4_title": "الحل الأكثر أمانا",
  "intro4_desc":
      "يتم متابعة وحدة الانقاذ لحظة بلحظة ومعرفة عدد الدقائق المتبقية حتي وصولها للعميل و متابعة السيارة الي المكان المتفق علية , و يتم مراقبة السيارة بكاميرا تصوير اونلاين اثناء النقل",
  "intro5_title": "الأسرع للوصول إليك",
  "intro5_desc":
      "توزيع السيارات بشكل جغرافي يضمن سرعة الوصول لتنفيذ الخدمات في أسرع وقت ",
  "accident desc": "وصف الحادث",
  "skip": "تخطي",
  "contact our customer support": "الإتصال بخدمة العملاء 17000",
  "attach police report page": "إرفاق محضر الشرطة",
  "before repair report page": "برجاء ارفاق مقايسة الإصلاح",
  "police report shooting comment": "ملاحظات تصوير محضر الشرطة",
  "before repair report shooting comment": "ملاحظات تصوير مقايسة الإصلاح",
  "please shoot clearly": "يرجي التصوير بشكل واضح",
  "shoot page by page": "يرجي التصوير تباعا صفحة صفحة",
  "shoot in good light": "يرجي التصوير في اضاءة مناسبة",
  "gallery": "معرض الصور",
  "Take Photos": "بدء التصوير",
  "air bags exploded": "الوسادات الهوائية المنفجرة",
  "glass defects": "اي نقر او شرخ بالزجاج الأمامي وغير واضح بالصور",
  "other damaged parts": "اي تلفيات أخري وغير واضحة بالصور",
  "vehicle shooting light": "التأكد من أن الاضاءة جيدة حول السيارة",
  "vehicle shooting distance":
      "البعد عن السيارة مسافة لاتقل عن متر ولاتزيد عن  متران",
  "vehicle shooting landscape":
      "وضع التصوير في الوضع الافقي مع اتباع تعليمات التطبيق",
  "please write accident desc": "يرجي كتابة وصف الحادث",
  "please confirm accident desc":
      "برجاء التأكد من اضافة وصف الحادث لتجنب رفض التقرير",
  "repair location added": "تم إضافة موقع الإصلاح",
  "repair location": "موقع الإصلاح",
  "Repair Location": "موقع الإصلاح",
  "bill delivery request": "طلب تسليم الفاتورة",
  "request delivery agent": "طلب مندوب",
  "bill delivery desc": "يمكنك طلب مندوب لتسليم الفاتورة للجهة المختصة",
  "bill delivery description": "برجاء تحديد الموعد والموقع لاستلام الفاتورة",
  "delivery location": "مكان استلام الفاتورة",
  "pickup date and time": "موعد استلام الفاتورة",
  "pickup date": "تاريخ استلام الفاتورة",
  "choose delivery time interval": "الفترة الزمنية المناسبة",
  "1-5 PM": "١ ظهرا - ٥ مساء",
  "09:00 AM - 01:00 PM": "٩ صباحا - ١ ظهرا",
  "add voice note": "اضف وصف صوتي",
  "voice description": "الوصف الصوتي للحادث",
  "Are you sure to delete the voice note?": "هل تريد حذف الملف الصوتي؟",
  "cancel": "الغاء",
  "Cancel": "الغاء",
  "Do you want to add Car(s) to your Package now?":
      ' عزيزي العميل هل تود في اضافة السيارة (أو السيارات ) المتمتعه بالباقة الان ؟ ',
  "Vehicle Chassis No. (optional)": "رقم الشاسيه (اختياري)",
  "please add comment or voice note":
      "برجاء اضافة وصف للحادث كتابة أو ملف صوتي",
  "repair location name": "اسم مكان الإصلاح",
  "additional info": "معلومات إضافية",
  "add vehicle corporate": "اضف سيارة",
  " (optional)": " (اختياري)",
  "add vehicle": "اضف سيارة",
  "deferredPayment": "الدفع آجل",
  "customer name": "اسم العميل بالكامل",
  "customer phone": "رقم تليفون العميل",
  "europeanTowTruck": "خدمة ونش منخفض",
  "choose towing service": "حدد نوع الونش",
  "basic towing": "عادي",
  "premium towing": "منخفض",
  "or": "أو",
  "Package Will be Active in Your Car After 72 Hours":
      ' يتم تفعيل خدمات الباقة علي السيارة بعد 72 ساعة',
  "Change": "تغيير",
  "Vaild Promo Code": "تم اعتماد الكود بنجاح",
  "Have Voucher Code?": "هل لديك قسيمة خصم؟",
  "Service is done": "تم الاتنهاء من الخدمه",
  "There is a problem please contact with call center":
      "هناك مشكله الرجاء التواصل مع خدمه العملاء",
  "Accept Request": "الموافقة على الطلب",
  "Validate": "تأكيد",
  "Did you finish": "هل انهيت الخدمة؟",
  "Start Service": "هل بدأت الخدمه؟",
  "has the car been repaired in the specified place as stated in before repair report":
      'هل تم اصلاح السيارة في الموقع المحدد للمعانية قبل الاصلاح ؟',
  "choose your package": "إختار الباقه",
  "I have a service card": "لدي كارت خدمات",
  "Insurance appendix": "ملحق بويثقه التأمين",
  "annual package": "الباقه السنويه - سياره واحده",
  "200 pounds": "200 جنيه مصري / سنويا",
  "family package": "الباقة العائلية - 2 سياره",
  "250 pounds": "250 جنيه مصري / سنويا",
  "family package 2": "الباقة العائلية - 3 سيارات",
  "300 pounds": "300 جنيه مصري / سنويا",
  "Continue without subscribing": "الاتسمرار بدون اشتراك",
  "Okay": "حسنا",
  "Feature 1": "الميزة رقم ١ على مدار العام",
  "package is activated successfully": "تم تفعيل الباقه بنجاح",
  "start to register cars": "البدء في تسجيل السيارات",
  "yes now": "نعم الان",
  "Insurance policy number": "رقم وثيقه التامين",
  "Please capture car license from both sides":
      "برجاء تصوير رخصه السياره من الجهتين",
  "Choose the insurance company and add a document":
      "اختيار شركه التامين و اضافه وثيقه",
  "In Case Adding Car to Package you Have to Add Plate Number":
      "في حالة اضافه السيارة الى الباقة يرجى ادخال رقم اللوحة",
  "Add this Car to The Active Package": "اضافه السيارة الى الباقات",
  "Vehicle Chassis No.": "رقم الشاسيه",
  "welcome to helpoo": "مرحبا بكم في هيلبو",
  "User already exist": "المستخدم موجود بالفعل",
  "Your account isn\'t activated yet": 'حسابك غير مفعل بعد',
  "Car Added Successfully": "تم اضافه السيارة بنجاح",
  "Car Not Added": " لم يتم اضافه السياره",
  "OTP Send Succesfully": "تم ارسال الكود بنجاح",
  "please select Service first": "برجاء اختيار الخدمه اولا",
  "Enter Promo Code": "ادخل الكود",
  "Name Required": "الاسم مطلوب",
  "hello": "مرحبا",
  "Success": "نجاح",
  // "Promo Code Applied Successfully": "تم تطبيق الكود بنجاح",
  "Update": "تحديث",
  "Only Insurance Company Can Edit": "فقط شركه التامين يمكنها التعديل",
  "Activate Package": "تفعيل الباقه",
  "Wench Service": "خدمه الونش",
  "wench": "ونش",
  "You Already Subscribed With This Packages":
      "لقد قمت بالاشتراك بالفعل مع هذه الباقات",
  "Do you Want to Add New Package?": "هل تريد اضافه باقه جديده؟",
  "I Already have Package": "لدي باقه بالفعل",
  "With car Insurance Policy": "مع وثيقه التامين",
  "Continue Without Subscribtion": "المتابعه بدون اشتراك",
  "Call 17000": "اتصل ب 17000",
  "Add to Package": "اضافه الى الباقه",
  "Add Users": "اضافه مستخدمين",
  "status": "حاله الخدمه",
  "Account Created Succesfully": "تم انشاء الحساب بنجاح",
  "Logout": "تسجيل الخروج",
  "Profile Updated Successfully": "تم تحديث الملف الشخصي بنجاح",
  "Created Successfully": "تم الانشاء بنجاح",
  "Get Driver success": "تم استرحاع بيانات السائق",
  "Car updated Successfully": "تم تحديث بيانات السياره",
  "No Drivers Avaliable": "لا يوجد سائقين",
  "There isn't Plate No.": "لا يوحد رقم لوحة",
  "please select type": "برجاء اختيار النوع",
  "please select model": "برجاء اختيار الموديل",
  "please select color": "برجاء اختيار اللون",
  "Right Save Report Updated": "تم تحديث تقرير حفظ الحق",
  "Right save inspection location": "موقع معاينة حفظ الحق",
  "You are using this promo": "انت تستخدم هذا الكود",
  "promoCodeError": "حدث خطأ ما أو أن هذا الكود غير صحيح",
  "Are you sure": "هل انت متاكد ؟",
  "Pay": "الدفع",
  "Driver Name": "اسم السائق",
  "Add Your Comment Here": "اضف تعليقك هنا",
  "choose Payment Method": "اختر طريقة الدفع",
  "Request Cancelled Successfully": "تم إلغاء الطلب بنجاح",
  "Please choose destination": "برجاء اختيار الوجهه",
  "Please choose origin": "برجاء اختيار المكان الأصل",
  "Km": "كم",
  "waring": "تحذير",
  "Please enter plate number": "برجاء ادخال رقم اللوحة",
  "Promo Code": "كود الخصم",
  "Promo Code Applied Successfully": "تم تطبيق الكود الخصم بنجاح",
  "Waiting Time": "وقت الانتظار",
  "Arrived to Destination": "وصلت الى الوجهه",
  "otp is required": "الكود مطلوب",
  "otp must be 4 digits": "الكود يجب ان يكون ٤ ارقام",
  "Please Select one Option to Continue": "برجاء اختيار احد الخيارات للمتابعه",
  "Online Payment With Visa": "الدفع أونلاين بالفيزا",
  "please enter comment or voice description": "برجاء ادخال تعليق او وصف صوتي",
  "click here to choose Address": "اضغط هنا لاختيار العنوان",
  "current billing date": "تاريخ التسليم الحالي : ",
  "Insert VIN that return in the vehicle license":
      "برجاء تدوين رقم الشاسيه المدون برخصة السيارة",
  "You Already Subscribed To The Following Packages":
      "لقد قمت بالاشتراك بالفعل مع الباقات التاليه",
  "please select payment method": "برجاء اختيار طريقة الدفع",
  "dest_arrived": "تم الوصول الى الوجهه",
  "wench number": "رقم الونش",
  "A new update is available. Please update the app to enjoy the latest features.":
      "توجد تحديثات جديده\n برجاء تحديث التطبيق للاستمتاع بأحدث المميزات",
  "Unknown device": "جهاز غير معروف",
  "The app is under maintenance. Please Contact the call center":
      "التطبيق تحت الصيانه\n برجاء الاتصال بخدمه العملاء",
  "Location services are disabled.": "خدمات الموقع معطله",
  "Location permissions are denied": "تم رفض صلاحيات الموقع",
  "Location permissions are permanently denied, we cannot request permissions.":
      "تم رفض صلاحيات الموقع بشكل دائم",
  "Enable permanent location": 'تفعيل الموقع الدائم',
  "please unable background location permission":
      'برجاء تفعيل صلاحيات الموقع في الخلفية',
  'Location permissions are only while use, we cannot request permissions in background.':
      'صلاحيات الموقع فقط أثناء الاستخدام ، ولا يمكننا طلب صلاحيات في الخلفية.',
  "failed to send notification after 5 retries":
      'فشل في إرسال الإشعار بعد 5 محاولات',
  "Please Wait": 'برجاء الانتظار',
  "to Send New OTP": 'لإرسال كود جديد',
  "Sec": 'ثانيه',
  "Invalid number": 'رقم غير صحيح',
  "Something Went Wrong": 'حدث خطأ ما',
  "something Wrong": 'حدث خطأ ما',
  "Plate Number is Required": 'رقم اللوحه مطلوب',
  "Front license Side is Required": 'صوره الرخصه الاماميه مطلوبه',
  "Back license Side is Required": 'صوره الرخصه الخلفيه مطلوبه',
  "Could not launch url": 'لا يمكن فتح الرابط',
  "whatsapp no installed": 'برجاء تثبيت الواتس اب',
  "Add Package": 'اضافه باقه',
  'Please Choose Package': 'برجاء اختيار الباقه',
  'choose language': 'اختر اللغه',
  'Please enter at least 5 characters': 'برجاء ادخال 5 احرف على الاقل',
  'You Have to enter company and policy number':
      'برجاء ادخال رقم الشركه ورقم البوليصه',
  'Email is not valid': 'البريد الالكتروني غير صحيح',
  "Repair Inspection": "معاينة الإصلاح",
  "Please enable location service": "برجاء تفعيل خدمة الموقع",
  'FNOL Creating Failed': 'فشل في إنشاء FNOL',
  'Done and Confirm Repair Location': 'تم تأكيد موقع الإصلاح',
  "Did you made Police Report?": "هل قمت بعمل تقرير شرطة؟",
  "Please add vehicle first": "برجاء اضافه السياره اولا",
  "You are blocked": "تم حظرك",
  "Are you sure you want to exit?": "هل انت متأكد من الخروج؟",
  'Subscription Done Successfully': 'تم الاشتراك بنجاح',
  'Could not Make Call': 'لا يمكن الاتصال',
  'Waiting for client confirmation': 'في انتظار تأكيد العميل',
  'text': 'نص',
  'no location name': 'لا يوجد اسم موقع',
  'Resurvey report page': 'برجاء إضافة تقرير مقايسة إضافية',
  'Supplement report page': 'برجاء إضافة  تقرير معاينة جديدة',
  'Please wait': 'برجاء الانتظار',
  'Required': 'مطلوب',
  'Take': 'تصوير',
  'Payment Done Successfuly': 'تم الدفع بنجاح',
  'Please Choose Payment Method': 'برجاء اختيار طريقة الدفع',
  'This Feature Underdevelopment': 'هذه الميزة قيد التطوير',
  'Checking...': 'جاري التحقق...',
  'in order to cancel your request please call 17000':
      'لإلغاء طلبك ، يرجى الاتصال بالرقم 17000',
  'Wrong Car, Please Call 17000': 'سيارة خاطئة ، يرجى الاتصال بالرقم 17000',
  'You Can\'t Edit This Car': 'لا يمكنك تعديل هذه السيارة',
  "No Summary Data": "لا يوجد بيانات لعرضها",
  "This feature is not available for corporate users":
      "هذه الميزة غير متاحة لمستخدمين الشركات",
  "promoApplySuccess": "تم تطبيق الكود بنجاح",
  'please Call 17000' : 'برجاء الاتصال بخدمة العملاء',
};
