const Map<String, String> en = {
  "Helpoo": "helpoo",
  "next": "Next",
  "instructions": "Photos Instructions",
  "enter": "Enter",
  "Login": "Login",
  "Home": "Home",
  "Add": "Add",
  "NO": "NO",
  "Choose Payment": "Choose Payment",
  "Loading......": "Loading......",
  "card-to-driver": "card-to-driver",
  "Yes": "Yes",
  "Tap To Open Report": "Tap To Open Report",
  "Accident Reports": "Accident Reports",
  "online-card": "online-card",
  "please complete missing data": "please complete missing data",
  "Choose the insurance company and add a VIN Number":
      "Choose the insurance company and add a VIN Number",
  "VIN Number": "VIN Number",
  "Select Company": "Select Company",
  "Please Select Destination": "Please Select Destination",
  "Insurance Policy Number": "Insurance Policy Number",
  "Insurance Company": "Insurance Company",
  "Choose insurance company": "Choose insurance company",
  "Inspection Location": "Inspection Location",
  "After Repair Report Updated": "After Repair Report Updated",
  "Is your Car Repaired and Ready for Inspection?":
      "Is your Car Repaired and Ready for Inspection?",
  "Bill Delivery Location": "Bill Delivery Location",
  "At time Range": "At time Range",
  "Bill Will Deliver At": "Bill Will Deliver At",
  "Final Data": "Final Data",
  "Billing Request Delivery Received": "Billing Request Delivery Received",
  "Reinspection Report Uploaded": "Reinspection Report Uploaded",
  "Supplement Report Uploaded": "Supplement Report Uploaded",
  "Before Repair Report Uploaded": "Before Repair Report Uploaded",
  "Request": "Request",
  "Did the Vehicle Deliverd to the Work Shop and the Quotation is Ready for the Inspection?":
      "Did the Vehicle Deliverd to the Work Shop and the Quotation is Ready for the Inspection?",
  "Your Request has Recieved Successfully and it will be Submitted within 24 hours":
      "Your Request has Recieved Successfully and it will be Submitted within 24 hours",
  "Next Step": "Next Step",
  "Vehicle Confirmation Data": "Vehicle Confirmation Data",
  "Not Avaliable Yet": "Not Avaliable Yet",
  "Plate No.": "Plate No.",
  "Description": "Description",
  "Additional Photos": "Additional Photos",
  "FNOL Uploaded": "FNOL Uploaded",
  "FNOL Follow Up": "FNOL Follow Up",
  "Bill Delivery Request": "Bill Delivery Request",
  "Billing Delivery": "Billing Delivery",
  "Right Save Inspection": "Right Save Inspection",
  "After Repair Inspection": "After Repair Inspection",
  "After Repair Inspections": "After Repair Inspections",
  "New Inspection request": "New Inspection request",
  "Additional Inspection": "Additional Inspection",
  "Before Repair Request": "Before Repair Request",
  "Before Repair Inspections": "Before Repair Inspections",
  "Add Policy Report": "Add Policy Report",
  "Police Report": "Police Report",
  "Please Choose Next Step": "Please Choose Next Step",
  "Trip Canceled": "Trip Canceled",
  "You are Blocked": "You are Blocked",
  "Something Wrong": "Something Wrong",
  "Accident Report": "Accident Report",
  "vehicle Service Request": "vehicle Service Request",
  "Welcome": "Welcome",
  "Have Voucher Code?": "Have Voucher Code?",
  "Chase Number (optional)": "Chase Number (optional)",
  "You have no requests now": "You have no requests now",
  "username": "Username",
  "Insurance policy appendix": "Insurance policy appendix",
  "Already Have Main Package": "Already Have Main Package",
  "Package Subscription": "Package Subscription",
  " (optional)": " (optional)",
  "password": "Password",
  "Full Name": "Full Name",
  "Language": "Language",
  "Logout": "Logout",
  "Settings": "Settings",
  "FNOL Done Successfully Uploading in Proccess":
      "FNOL Done Successfully\n Uploading in Proccess",
  "FNOL Save": "FNOL Save",
  "request service": '''Request
Service''',
  "accident report": '''Report an
Accident''',
  "pre-inception": '''Pre-
Inception''',
  "Request Service": "Request Service",
  "Select vehicle": "Select vehicle",
  "Batteries faults": "Batteries",
  "Tires faults": "Tires Fix",
  "Fuel faults 5L": "Fuel Problem",
  "Fuel faults 10L": "Fuel 10 Liters",
  "Towing": "vehicle Towing",
  "Request ID : ": "Request ID",
  "canceled": "Cancelled",
  "notAvailable": "Service not available now",
  "open": "Open",
  "confirmed": "Confirmed",
  "not_available": "Not Available",
  "accepted": "Driver on the way",
  "done": "Done",
  "Done": "Done",
  "started": "Service in Progress",
  "view": "View",
  "request status": "Request Status",
  "fees": "Fees",
  "requested services": "Requested Services",
  "client": "Client",
  "select pickup Address": "Select Pickup Address",
  "select dropoff Address": "Select Dropoff Address",
  "pickup Address": "Pickup Address",
  "dropoff Address": "Dropoff Address",
  "estimate route distance": "Distance",
  "estimate route duration": "Time",
  "EGP": "EGP",
  "Active": "Active",
  "Inactive": "Inactive",
  "Select Location": "Select Location",
  "Select Address": "Select Address",
  "Submit": "Submit",
  "Promo Code Valid till": "Promo Code Valid till",
  "view current request": '''View Current
Request''',
  "please wait for driver to accept your request":
      "Waiting for Driver to accept your request",
  "Request Details": "Request Details",
  "distance to dropoff": "Distance to Dropoff",
  "time to dropoff": "Time to reach Dropoff Address",
  "confirm": "Confirm",
  "Payment Success": "Payment Success",
  "You Can Add Cars Now": "You Can Add Cars Now",
  "cancel request": "Cancel Request",
  "Call Driver": "Call Driver",
  "Dropoff Directions": "Dropoff Directions",
  "Pickup Directions": "Pickup Directions",
  "are you sure?": "Are You Sure?",
  "yes": "Yes",
  "search": "Search",
  "You are offline": "You are not connected to Internet",
  "Retry": "Retry",
  "history": "My Requests",
  "estimate remaining distance": "Distance remaining to arrive",
  "estimate remaining duration": "Time remaining to arrive",
  "Permissions": "Permissions",
  "helpoo collects location data to enable finding the nearest RSA unit. the location data is collected while the app is in use or the app is in the background":
      "helpoo collects location data to enable finding the nearest RSA unit. the location data is collected while the app is in use or the app is in the background",
  "Disable Battery Optimisation": "Disable Battery Optimization",
  "Allow Location Access": "Allow Location Access",
  "vehicle is being towed": "vehicle is being towed",
  "back": "Back",
  "address": "Address",
  "destination": "Destination",
  "on the way to client": "on the way to client",
  "find vehicle": "Find vehicle",
  "Plate NO. (optional)": "Plate NO. (optional)",
  "Notify An Accident (FNOL)": "Notify An Accident (FNOL)",
  "number": "Number",
  "error": "Error",
  "Error": "Error",
  "Details": "Details",
  "vehicle not found": "No vehicle matches this plate number",
  "create report": "Create Report",
  "reports history": '''Reports
History''',
  "select accident type": "Select Accident Type",
  "accident report ": "Accident Report",
  "Accident Types": "Accident Types",
  "vehicle owner": "vehicle Owner",
  "Please select": "Please Select",
  "insurance company": "Insurance",
  "name must be at least 3 characters": "Name must be at least 3 characters",
  "required field": "Required Field",
  "phone number length must be 11 degits":
      "Phone number length must be 11 degits",
  "phone number": "Phone Number",
  "report details": "Report Details",
  "new report": "New Report",
  "reports history ": "Requests History",
  "comment": "Comment",
  "Data Confirmation": "Data Confirmation",
  "police report": "Police Report",
  "before repair report": "Before Repair Report",
  "after repair report": "After Repair Report",
  "request report": "Request Assessment",
  "Extra Photos": "Additional Photos",
  "Extra Photos description":
      "Please shoot additional Photos in the following cases",
  "photos": "Photos",
  "Replace Promo Code": "Replace Promo Code",
  "save": "Save",
  "Please capture the front side of the vehicle licence":
      "Please capture the front side of the vehicle licence",
  "Please capture the back side of the vehicle licence":
      "Please capture the back side of the vehicle licence",
  "Data Saved Successfully": "Data Saved Successfully",
  "repair cost": "Repair Cost",
  "save cost": "Save Cost",
  "current reports": "Current Reports",
  "closed reports": "Finished Reports",
  "vehicle owner name": "vehicle Owner Name",
  "add comment": "Add Comment",
  "edit comment": "Edit Comment",
  "finish": "Finish",
  "send report": "Send Report",
  "choose accident type": "Select Damaged Parts",
  "damaged parts": "Damaged Parts",
  "Please select one or more type": "Please select one or more accident types",
  "none": "None",
  "More": "More",
  "ontinue Without Subscribtion": "ontinue Without Subscribtion",
  "This Service Will be Avaiable Soon": "This Service Will be Avaiable Soon",
  "confirm entered data": "Confirm",
  "accident location": "Accident Location",
  "reports": "Reports",
  "Service vehicle": "Service vehicle",
  "Scooter": "Scooter",
  "Towing vehicle": "Towing vehicle",
  "meters": "meters",
  "getting your address": "Please wait while we detect your location",
  "Set Location on Map": "Set Location on Map",
  "m": "m",
  "km": "km",
  "Please Allow Location Access": "Please Enable Location",
  "Check Again": "Check Again",
  "Register New Account": "Register New Account",
  "Wrong username or password": "Wrong username or password",
  "forgot password?": "Forgot Password?",
  "register new account": "Register New Account",
  "enter registered phone": "Please enter your phone number",
  "confirm phone number": "Confirm Phone Number",
  "enter otp": "Please Enter OTP",
  "please confirm info": "Please Confirm Information",
  "Add Vehicle": "Add Vehicle",
  "full name": "Full Name",
  "email": "Email",
  "vehicle type": "Vehicle Type",
  "year of manufacture": "Year",
  "model": "Model",
  "color": "Color",
  "You Have No Requests For Now": "You Have No Requests For Now",
  "invalid OTP": "Wrong OTP",
  "invalid otp": "Wrong OTP",
  "Wrong Phone Number": "Wrong Phone Number",
  "set password": "Set Password",
  "enter password": "Please, Enter Password",
  "password confirmation": "Password Confirmation",
  "password length": "Password at least 8 characters",
  "account success": "Account Created Succesfully",
  "password mismatch": "Password does not match",
  "invalid phone number": "Invalid Phone Number",
  "White": "White",
  "pay driver using credit card": "pay driver using credit card",
  "credit card": "credit card",
  "Dear Client, Do You want to Register your vehicles Now to Save Time When you Need Urgent Service?":
      "Dear Client, Do You want to Register your vehicles Now to Save Time When you Need Urgent Service?",
  "Black": "Black",
  "Gray": "Grey",
  "Silver": "Silver",
  "Red": "Red",
  "Blue": "Blue",
  "Brown": "Brown",
  "Green": "Green",
  "Beige": "Beige",
  "Orange": "Orange",
  "Gold": "Gold",
  "Yellow": "Yellow",
  "Purple": "Purple",
  "Enter Email Address": "Enter Email Address",
  "Enter Promo Code if Exist (optional)":
      "Enter Promo Code if Exist (optional)",
  "If you Have Promo Code, Please insert (optional)":
      "If you Have Promo Code, Please insert (optional)",
  "invalid email": "Invalid Email",
  "error, number 10 - 9999": "Invalid Number",
  "please enter a valid manufacturer and vehicle model":
      "Please Choose vehicle Type & Model",
  "please enter a valid color": "Please Select vehicle Color",
  "vehicle already added": "vehicle added before",
  "please select year": "Please Select Manufacture Year",
  "Edit vehicle data": "Edit Vehicle Data",
  "invalid name": "not less than 3 letters",
  "reset password page": "Reset Password",
  "Yes Now": "Yes Now",
  "please enter phone number": "Please Enter Phone Number",
  "continue": "Continue",
  "Continue": "Continue",
  "phone number is not registered": "This Number is not registered",
  "pleae try again": "Please Try Again",
  "password reset success": "Password changed successfully",
  "please enter a valid plate number": "Please Enter valid Plate Number",
  "please select insurance company": "Please Select Insurance Company",
  "vehicle added": "vehicle added successfully",
  "confirm payment": "Confirm Payment",
  "Did you recieve the payment?": "Did you recieve the payment ?",
  "service fees is": "Service Fess are",
  "please edit vehicle to set plate number first":
      "Please Add vehicle Plate Number",
  "please select services first": "Please Select Service",
  "paid": "Paid",
  "Vehicle Plate No.": "Vehicle Plate No.",
  "main screen": "Main",
  "please select service": "Please Select Service",
  "road services": "Road Services",
  "ambulance": "Ambulance",
  "police": "Police",
  "latest request": "Latest Requests",
  "latest reports": "Latest Reports",
  "about app": "About",
  "my vehicles": "My vehicles",
  "packages": "Packages",
  "Please Choose Destination": "Please Choose Destination",
  "contact us": "Contact Us",
  "not available yet": "Service is not available yet and will be launched soon",
  "please select vehicle first": "Please Select vehicle",
  "Select Your Location": "Select Your Location",
  "current location": "Current Location",
  "towing destination": "Towing Destination",
  "select payment method": "Select Payment Method",
  "payment after service is done": "Payment After Service",
  "pay driver using credit vehicled": "Pay using Credit to Driver",
  "pay driver using cash": "Pay Driver in Cash",
  "visa master card": "(Visa - Master vehicled - Meeza)",
  "service status": "Service Status",
  "no requests to show": "No Past Requests",
  "no reports to show": "No Past Reports",
  "arrival time": "Arrival Time",
  "distance": "Distance",
  "total cost": "Total Cost",
  "basic cost": "Basic Cost",
  "minute": "Minute",
  "egp": "EGP",
  "min": "min",
  "cash": "Cash",
  "vehicledToDriver": "vehicled to Driver",
  "vehicled": "Credit vehicled",
  "wallet": "Mobile Wallet",
  "please rate the driver": "Please Rate The Driver",
  "please click on cancel request button":
      "Please Click on Cancel Request Button",
  "sure you want to cancel": "Do You Want to Cancel the Request",
  "cancel confirmation text":
      "You can cancel the order at any time and no fines will be applied, but avoid repeated cancellation because it exposes you to closing your account permanently and you will not be able to open the account again",
  "resume": "Resume",
  "paid success": "Paid Successfully",
  "available": "Available",
  "rate driver": "Rate Driver",
  "Resume Accident Report": "Resume Accident Report",
  "discount": "Discount",
  "hour": "hour",
  "hours": "hours",
  "sec": "sec",
  "mins": "min",
  "Choose Damaged Vehicle": "Choose Damaged Vehicle",
  "Choose one or more Accident Type": "Choose one or more Accident Type",
  "You don't have registered insured vehicle":
      "You don't have registered insured vehicle",
  "accident Photos": "Accident Photos",
  "attach": "Attach",
  "edit": "Edit",
  "Edit": "Edit",
  "add": "Add",
  "Save": "Save",
  "Change": "Change",
  "no police report yet": "No Police Report Yet",
  "no repair report yet": "No Repair Report Yet",
  "arrived": "Driver arrived",
  "Arrived": "Arrived",
  "pay using mobile wallet": "Smart Wallet",
  "pay using online vehicled": "Credit vehicled",
  "Please Enter Mobile Number for Payment":
      "Please Enter Mobile Number for Payment",
  "Pay with Mobile Wallet": "Pay with Mobile Wallet",
  "change language": "Change Language",
  "package name": "Package Name",
  "allowed times": "Allowed Usage Times",
  "maximum discount": "Maximum Discount / Request",
  "discount percentage": "Discount Percentage",
  "price": "Price",
  "Please Confirm Vehicle(s) Data": "Please Confirm Vehicle(s) Data",
  "Buy Package": "Subscribe",
  "View Package": "View Package",
  "for report number ": "For Report Number ",
  "are you sure the vehicle has been repaired and ready to assess?":
      "are you sure the vehicle has been repaired and ready to assess?",
  "no": "No",
  "has the vehicle been repaired in the specified place as stated in before repair report?":
      "Has the vehicle been repaired in the specified place as stated in before repair report?",
  "please contact our customer support": "Please contact our Customer Support",
  "customer support": "Customer Support",
  "call": "Call",
  "Wench": "Wench",
  "Battery": "Battery",
  "Profile": "Profile",
  "Valid Promo Code": "Valid Promo Code",
  "Later": "Later",
  "Vehicle Chassis No. (optional)": "Vehicle Chassis No. (optional)",
  "your request has been received": "Your request has been received",
  "resend": "Resend OTP",
  "current package": "My Package",
  "start date": "Start Date",
  "end date": "End Date",
  "used times": "Number of Requests used",
  "times": " Times",
  "payment status": "Payment Status",
  "pending": "Pending",
  "account already exists, please go to login or reset your password":
      "account already exists, please go to login or reset your password",
  "sorry, we don't have inspectors available now":
      "sorry, we don't have inspectors available now",
  "sorry, service is not available now": "sorry, service is not available now",
  "send whatsapp message": "Send Message via Whatsapp",
  "call customer support": "Call Customer Support",
  "send email": "Send us an Email",
  "Not Insured Text": "This vehicle in Not Insured",
  "Insured Text": "This vehicle enjoys helpoo's services till",
  "take photo": "Take Photo",
  "Retake": "Retake",
  "next photo": "Next Photo",
  "done shooting": "Finish",
  "intro1_title": "24/7 Coverage",
  "intro1_desc":
      "All services are  accessible every day of the week 24/7, including holidays.",
  "intro2_title": "The Easiest",
  "intro2_desc":
      "All road assist vehicles are outfitted with complete tracking and communication systems; thus, helpoo application allows you to track the road assist vehicle till arrival, moment by moment, using google maps.",
  "intro3_title": "Most Budget Friendly",
  "intro3_desc":
      "Service cost will be estimated, in advance, based on the distance through Google Maps, without any blackmail or taking advantage of the circumstance, before approving and confirming the service.",
  "intro4_title": "The Safest",
  "intro4_desc":
      "No need to accompany the road assist vehicle, during the transportation process, as the customer can track it through his mobile app, also the whole trip is monitored & recorded by Cameras fitted to the road assist vehicle.",
  "intro5_title": "The Fastest",
  "intro5_desc":
      "The geographical distribution of RSA units ensures quick access to the implementation of services in the fastest time",
  "accident desc": "Accident Description",
  "skip": "Skip",
  "police Report Uploaded": "police Report Uploaded",
  "Uploading Percentage": "Uploading Percentage",
  "Send Request": "Send Request",
  "Add Report": "Add Report",
  "Have reinspection Report? Please Add it":
      "Have reinspection Report? Please Add it",
  "Have supplement Report? Please Add it":
      "Have supplement Report? Please Add it",
  "Have before Repair Report? Please Add it":
      "Have before Repair Report? Please Add it",
  "Plate NO.": "Plate NO.",
  "Vaild Promo Code": "Vaild Promo Code",
  "contact our customer support": "Contact Customer Support 17000",
  "attach police report page": "Please attach the Police Report",
  "before repair report page": "Please attach the Repair Assay",
  "police report shooting comment": "Imaging notes for the Police Report",
  "before repair report shooting comment": "Imaging notes for the Repair Assay",
  "please shoot clearly": "Please photograph clearly",
  "shoot page by page": "Please photograph page by page",
  "shoot in good light": "Please photograph in appropriate lighting",
  "gallery": "Photo Gallery",
  "Take Photos": "Take Photos",
  "air bags exploded": "Exploded airbags",
  "glass defects":
      "Any cracks or cracks in the windshield, which are not visible in the Photos",
  "other damaged parts": "Any other damages that are not clear in the Photos",
  "vehicle shooting light":
      "Ensure that there is good lighting around the vehicle",
  "vehicle shooting distance":
      "The distance from the vehicle is not less than one meter and not more than two metres",
  "vehicle shooting landscape":
      "Shooting mode is in landscape mode, following the application instructions",
  "please write accident desc": "Please write Accident Description",
  "please confirm accident desc":
      "Please make sure to add accident description to avoid report neglection",
  "repair location added": "Repair Location Added",
  "repair location": "Repair Location",
  "Repair Location": "Repair Location",
  "bill delivery request": "Bill Delivery Request",
  "request delivery agent": "Request an Agent",
  "bill delivery desc":
      "You can request a representative to deliver the invoice to the competent authority",
  "bill delivery description":
      "Please specify the location and date of delivery",
  "delivery location": "Delivery Location",
  "pickup date and time": "Pickup date & time",
  "pickup date": "Pickup date",
  "choose delivery time interval": "Appropriate time period",
  "01:00 PM - 05:00 PM": "01:00 PM - 05:00 PM",
  "09:00 AM - 01:00 PM": "9 AM - 1 PM",
  "add voice note": "Add Voice Description",
  "voice description": "Accident Description Voice",
  "Are you sure to delete the voice note?":
      "Do you want to delete voice record?",
  "cancel": "Cancel",
  "Cancel": "Cancel",
  "please add comment or voice note":
      "Please add accident description written or voice",
  "repair location name": "Repair Location Name",
  "additional info": "Additional Info",
  "add vehicle corporate": "Add vehicle",
  "deferredPayment": "Deferred",
  "customer name": "Customer Full Name",
  "customer phone": "Customer Phone Number",
  "europeanTowTruck": "Premium vehicle Towing",
  "choose towing service": "Choose Wench Type",
  "basic towing": "Normal",
  "premium towing": "Premium",
  "or": "OR",
  "Insert VIN that return in the vehicle license":
      "Insert VIN that return in the vehicle license",
  "Tire Problem": "Tire Problem",
  "Add More Vehicle(s)": "Add More Vehicle(s)",
  "After Discount": "After Discount",
  "Before Discount": "Before Discount",
  "Deferred": "Deferred",
  "Voucher Code": "Voucher Code",
  "Service is done": "Service is done",
  "There is a problem please contact with call center":
      "There is a problem please contact with call center",
  "Accept Request": "Accept Request",
  "Validate": "Validate",
  "Did you finish": "Did you finish?",
  "Start Service": "Started",
  "has the car been repaired in the specified place as stated in before repair report":
      "has the car been repaired in the specified place as stated in before repair report؟",
  "choose your package": "choose your package",
  "I have a service card": "I have a service card",
  "Insurance appendix": "Insurance appendix",
  "annual package": "annual package - 1 car",
  "pending request": "You should call support to complete your request",
  "request is pending": "Request is pending : ",
  "200 pounds": "200 LE / Annually",
  "family package": "family package - 2 cars ",
  "250 pounds": "250 LE / Annually",
  "family package 2": "family package - 3 cars ",
  "300 pounds": "300 LE / Annually",
  "Continue Without Subscribtion": "Continue Without Subscribtion",
  "Okay": "Okay",
  "Activate": "Activate",
  "Package Will be Active in Your Car After 72 Hours":
      "Package Will be Active in Your Car After 72 Hours",
  "Do you want to add Car(s) to your Package now?":
      "Do you want to add Car(s) to your Package now?",
  "Feature 1": "Feature 1 of the year",
  "package is activated successfully": "package is activated successfully",
  "start to register cars": "start to register cars",
  "yes now": "yes now",
  "Insurance policy number": "Insurance policy number",
  "Please capture car license from both sides":
      "Please capture car license from both sides",
  "Choose the insurance company and add a document":
      "Choose the insurance company and add a document",
  "In Case Adding Car to Package you Have to Add Plate Number":
      "In Case Adding Car to Package you Have to Add Plate Number",
  "Add this Car to The Active Package": "Add this Car to The Active Package",
  "Vehicle Chassis No.": "Vehicle Chassis No.",
  "welcome to helpoo": "welcome to helpoo",
  "User already exist": "User already exist",
  "Your account isn\'t activated yet": "Your account isn\'t activated yet",
  "Car Added Successfully": "Car Added Successfully",
  "Car Not Added": "Car Not Added",
  "OTP Send Succesfully": "OTP Send Succesfully",
  "please select Service first": "please select Service first",
  "Enter Promo Code": "Enter Promo Code",
  "Name Required": "Name Required",
  "hello": "hello",
  "Please fill in the required items": "Please fill in the required items",
  "Success": "Success",
  "Update": "Update",
  "Only Insurance Company Can Edit": "Only Insurance Company Can Edit",
  "Activate Package": "Activate Package",
  "Wench Service": "Wench Service",
  "You Already Subscribed With This Packages":
      "You Already Subscribed With This Packages",
  "Do you Want to Add New Package?": "Do you Want to Add New Package?",
  "I Already have Package": "I Already have Package",
  "With car Insurance Policy": "With car Insurance Policy",
  "Call 17000": "Call 17000",
  "Add to Package": "Add to Package",
  "Add Users": "Add Users",
  "status": "status",
  "Profile Updated Successfully": "Profile Updated Successfully",
  "Created Successfully": "Created Successfully",
  "Get Driver success": "Get Driver success",
  "Car updated Successfully": "Car updated Successfully",
  "No Drivers Avaliable": "No Drivers Avaliable",
  "There isn't Plate No.": "There isn't Plate No.",
  "please select type": "Please select type",
  "please select model": "Please select model",
  "please select color": "Please select color",
  "Right Save Report Updated": "Right Save Report Updated",
  "Right save inspection location": "Right save inspection location",
  "You are using this promo": "You are using this promo",
  "promoCodeError": "Some thing Wrong or this Promo Code is not valid",
  "Are you sure": "Are you sure ?",
  "wench": "Wench",
  "Pay": "Pay",
  "Driver Name": "Driver Name",
  "Add Your Comment Here": "Add Your Comment Here",
  "choose Payment Method": "choose Payment Method",
  "Request Cancelled Successfully": "Request Cancelled Successfully",
  "Please choose destination": "Please choose destination",
  "Please choose origin": "Please choose origin",
  "Km": "KM",
  "Package Details": "Package Details",
  "Have Promo Code?": "Have Promo Code?",
  " LE / Yearly": " LE / Annually",
  "waring": "waring",
  "Please enter plate number": "Please enter plate number",
  "Promo Code": "Promo Code",
  "Promo Code Applied Successfully": "Promo Code Applied Successfully",
  "Waiting Time": "Waiting Time",
  "Arrived to Destination": "Arrived to Destination",
  "otp is required": "otp is required",
  "otp must be 4 digits": "otp must be 4 digits",
  "Please Select one Option to Continue":
      "Please Select one Option to Continue",
  "Online Payment": "Online Payment",
  "Online Payment With Visa": "Online Payment With Visa",
  "click here to choose Address": "click here to choose Address",
  "please enter comment or voice description":
      "please enter comment or voice description",
  "current billing date": "current billing date : ",
  "You Already Subscribed To The Following Packages":
      "You Already Subscribed To The Following Packages",
  "please select payment method": "please select payment method",
  "dest_arrived": "Arrived to Destination",
  "wench number": "Wench Num",
  "A new update is available. Please update the app to enjoy the latest features.":
      "A new update is available. Please update the app to enjoy the latest features.",
  "Unknown device": "Unknown device",
  "The app is under maintenance\n Please Contact the call center":
      "The app is under maintenance\n Please Contact the call center",
  "Location services are disabled.": "Location services are disabled.",
  "Location permissions are denied": "Location permissions are denied",
  "Location permissions are permanently denied, we cannot request permissions.":
      "Location permissions are permanently denied, we cannot request permissions.",
  "Enable permanent location": "Enable permanent location",
  "please unable background location permission":
      "please unable background location permission",
  'Location permissions are only while use, we cannot request permissions in background.':
      'Location permissions are only while use, we cannot request permissions in background.',
  "failed to send notification after 5 retries":
      "failed to send notification after 5 retries",
  "Please Wait": "Please Wait",
  "to Send New OTP": "to Send New OTP",
  "Sec": "Sec",
  "Invalid number": "Invalid number",
  "Something Went Wrong": "Something Went Wrong",
  "something Wrong": "something Wrong",
  'Plate Number is Required': 'Plate Number is Required',
  "Front license Side is Required": "Front license Side is Required",
  "Back license Side is Required": "Back license Side is Required",
  'Could not launch url': 'Could not launch url',
  "whatsapp no installed": "whatsapp no installed",
  "Add Package": "Add Package",
  'Please Choose Package': 'Please Choose Package',
  'choose language': 'Choose Language',
  'Please enter at least 5 characters': 'Please enter at least 5 characters',
  'You Have to enter company and policy number':
      'You Have to enter company and policy number',
  'Email is not valid': 'Email is not valid',
  "Repair Inspection": "Repair Inspection",
  "Please enable location service": "Please enable location service",
  'FNOL Creating Failed': 'FNOL Creating Failed',
  'Done and Confirm Repair Location': 'Done and Confirm Repair Location',
  "Did you made Police Report?": "Did you made Police Report?",
  "Fuel": "Fuel",
  "Tire": "Tire",
  "Please add vehicle first": "Please add vehicle first",
  "You are blocked": "You are blocked",
  'Are you sure you want to exit?': 'Are you sure you want to exit?',
  'Payment Process': 'Payment Process',
  'Subscription Done Successfully': 'Subscription Done Successfully',
  'Could not Make Call': 'Could not Make Call',
  'Waiting for client confirmation': 'Waiting for client confirmation',
  'text': 'text',
  'no location name': 'no location name',
  'Resurvey report page': 'Resurvey report page',
  'Supplement report page': 'Supplement report page',
  'Please wait': 'Please wait',
  'init': 'init',
  'Required': 'Required',
  'Billing Delivery Location': 'Billing Delivery Location',
  'Take': 'Take',
  'Payment Done Successfuly': 'Payment Done Successfuly',
  'Please Choose Payment Method': 'Please Choose Payment Method',
  'This Feature Underdevelopment': 'This Feature Underdevelopment',
  'Checking...': 'Checking...',
  'in order to cancel your request please call 17000':
      'in order to cancel your request please call 17000',
  'Wrong Car, Please Call 17000': 'Wrong Car, Please Call 17000',
  'You Can\'t Edit This Car': 'You Can\'t Edit This Car',
  "No Summary Data": "No Data to show",
  "This feature is not available for corporate users":
      "This feature is not available for corporate users",
  "promoApplySuccess": "Promo Code Applied Successfully",
  'please Call 17000' : 'Please Call Call Center',
};
